// vp_names.h - Viva Pinata engine functions identified from Trouble in Paradise.
// Generated by tools/port_names.py (exact and high matches only); do not edit.
// Full table: docs/NAMES_FROM_TIP.md. Names: TiP-Recomp (SolarCookies, with permission).
//
//   VP_FN_x   the generated function (weak alias: override it with REX_HOOK_RAW)
//   VP_IMP_x  the original recompiled body (always callable)
#pragma once

#define VP_FN_CXuiModule__ProcessInput sub_821BF330   // exact, TiP 0x8229A968
#define VP_IMP_CXuiModule__ProcessInput __imp__sub_821BF330
#define VP_FN_XInputGetKeystroke sub_826B85B8   // exact, TiP 0x82B0A740
#define VP_IMP_XInputGetKeystroke __imp__sub_826B85B8
#define VP_FN_camMainGetAspectRatio sub_82128B40   // exact, TiP 0x821F0730
#define VP_IMP_camMainGetAspectRatio __imp__sub_82128B40
#define VP_FN_XuiProcessInput sub_824B9CE0   // high, TiP 0x826B2DE0
#define VP_IMP_XuiProcessInput __imp__sub_824B9CE0
#define VP_FN_appErrorReportDirtyDisk sub_82101408   // high, TiP 0x821C4C48
#define VP_IMP_appErrorReportDirtyDisk __imp__sub_82101408
#define VP_FN_appMainDraw sub_821051A8   // high, TiP 0x821C8E78
#define VP_IMP_appMainDraw __imp__sub_821051A8
#define VP_FN_appMainTickPreDraw sub_82105528   // high, TiP 0x821C91C0
#define VP_IMP_appMainTickPreDraw __imp__sub_82105528
#define VP_FN_camMainGetPos sub_82128BE8   // high, TiP 0x821F07E0
#define VP_IMP_camMainGetPos __imp__sub_82128BE8
#define VP_FN_mathSin sub_8249DEF0   // high, TiP 0x8292A588
#define VP_IMP_mathSin __imp__sub_8249DEF0
#define VP_FN_meCreateRuffianActor sub_822BF8D8   // high, TiP 0x823F89E0
#define VP_IMP_meCreateRuffianActor __imp__sub_822BF8D8
#define VP_FN_meLoadAsset sub_8210BF18   // high, TiP 0x821D2120
#define VP_IMP_meLoadAsset __imp__sub_8210BF18
#define VP_FN_meUpdateOutputViewport sub_82129358   // high, TiP 0x821F0F30
#define VP_IMP_meUpdateOutputViewport __imp__sub_82129358
#define VP_FN_mlMtxPerspective sub_821712B8   // high, TiP 0x82247408
#define VP_IMP_mlMtxPerspective __imp__sub_821712B8
#define VP_FN_objMsgInit sub_82178588   // high, TiP 0x82250578
#define VP_IMP_objMsgInit __imp__sub_82178588
#define VP_FN_requirementsMet sub_823B09A8   // high, TiP 0x82537810
#define VP_IMP_requirementsMet __imp__sub_823B09A8
#define VP_FN_supportPinataCreateGeneralEx sub_823E3738   // high, TiP 0x82575C30
#define VP_IMP_supportPinataCreateGeneralEx __imp__sub_823E3738
#define VP_FN_supportPinataActorIsOnSurfaceWithPreference sub_823CEB10   // high, TiP 0x82558D28
#define VP_IMP_supportPinataActorIsOnSurfaceWithPreference __imp__sub_823CEB10
